pipeline {
    agent any

    stages {
        stage('stop the existing container') {
            steps {
                script {
                    def containerName = "codequant"
                    def containerStatus = sh(script: "docker inspect -f '{{.State.Status}}' ${containerName} || true", returnStdout: true).trim()
                    if (containerStatus == "running") {
                        sh "docker stop ${containerName}"
                        sh "docker rm ${containerName}"
                    } else {
                        echo "Container ${containerName} is not running"
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def imageName = "mockapp"
                    sh "docker build -t ${imageName} ./backend/src"
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    def containerName = "codequant"
                    def imageName = "mockapp"
                    sh "docker run -d -p 5000:5000 --name ${containerName} ${imageName}"
                }
            }
        }
    }
}
